const root=document.documentElement,body=document.body;
const page=body.dataset.page||"home";
if(document.querySelector("[data-nav]"))document.querySelector("[data-nav]").innerHTML=`<nav class="site-nav"><a class="brand" href="index.html"><i>C</i><span>CITY WORD<br><b>FAMILY CHURCH</b></span></a><div class="links"><a href="about.html">About</a><a href="ministries.html">Ministries</a><a href="events.html">Events</a><a href="sermons.html">Watch</a><a href="next-steps.html">Next Steps</a><a href="care.html">Care</a></div><a class="pill coral" href="contact.html">Plan your visit ↗</a><button class="menu" aria-label="Toggle navigation" aria-expanded="false">☰</button></nav>`;
if(document.querySelector("[data-footer]"))document.querySelector("[data-footer]").innerHTML=`<footer><div class="footer-lead"><a class="brand" href="index.html"><i>C</i><span>CITY WORD<br><b>FAMILY CHURCH</b></span></a><h2>There is a place<br>for <em>you.</em></h2></div><div class="footer-links"><div><b>EXPLORE</b><a href="about.html">Our Story</a><a href="ministries.html">Ministries</a><a href="events.html">Events</a><a href="sermons.html">Messages</a></div><div><b>CONNECT</b><a href="next-steps.html">Next Steps</a><a href="care.html">Pastoral Care</a><a href="contact.html">Plan a Visit</a><a href="giving.html">Give</a></div><div><b>YOUTH</b><a href="generations-shakers.html">Generations Shakers</a><a href="generations-shakers.html#stories">Stories</a><a href="generations-shakers.html#connect">Join the Movement</a></div><div><b>STAY IN THE LOOP</b><p>Hope, stories, and what’s coming up—straight to your inbox.</p><form><input type="email" placeholder="Your email address" aria-label="Email address"><button aria-label="Subscribe">→</button></form></div></div><p class="legal">© 2026 CITY WORD FAMILY CHURCH – ANTIPOLO <span>PRIVACY · TERMS</span></p></footer>`;
document.querySelectorAll(".links a").forEach(a=>{if(a.getAttribute("href").startsWith(page))a.classList.add("current")});
const menu=document.querySelector(".menu"),links=document.querySelector(".links");if(menu)menu.onclick=()=>{links.classList.toggle("open");menu.setAttribute("aria-expanded",links.classList.contains("open"))};
const bar=document.querySelector(".progress")||document.body.appendChild(Object.assign(document.createElement("div"),{className:"progress"}));addEventListener("scroll",()=>{bar.style.width=(scrollY/(document.documentElement.scrollHeight-innerHeight)*100)+"%";document.querySelector(".site-nav")?.classList.toggle("scrolled",scrollY>40)},{passive:true});
const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add("seen")}),{threshold:.14});document.querySelectorAll(".reveal,.story-card,.ministry-tile,.care-card,.impact-card").forEach(el=>io.observe(el));
document.querySelectorAll("[data-filter]").forEach(btn=>btn.onclick=()=>{document.querySelectorAll("[data-filter]").forEach(x=>x.classList.remove("active"));btn.classList.add("active");document.querySelectorAll("[data-category]").forEach(card=>card.hidden=btn.dataset.filter!=="all"&&card.dataset.category!==btn.dataset.filter)});
document.querySelectorAll(".accordion button").forEach(btn=>btn.onclick=()=>{const item=btn.parentElement;document.querySelectorAll(".accordion article").forEach(x=>x!==item&&x.classList.remove("open"));item.classList.toggle("open")});
document.querySelectorAll("[data-modal]").forEach(btn=>btn.onclick=()=>{const modal=document.querySelector(btn.dataset.modal);if(modal){modal.classList.add("open");modal.querySelector("input,select,textarea")?.focus()}});
document.querySelectorAll(".modal-close").forEach(btn=>btn.onclick=()=>btn.closest(".modal").classList.remove("open"));
document.querySelectorAll("form").forEach(form=>form.addEventListener("submit",e=>{e.preventDefault();const note=form.querySelector(".form-note");if(note)note.textContent="Thank you. Your request has been received in this demonstration."}));
const countdown=document.querySelector("[data-countdown]");if(countdown){const target=new Date(Date.now()+12*86400000+6*3600000);setInterval(()=>{let d=target-Date.now(),days=Math.floor(d/86400000),h=Math.floor(d/3600000)%24,m=Math.floor(d/60000)%60;countdown.innerHTML=`<b>${days}<small>DAYS</small></b><b>${h}<small>HOURS</small></b><b>${m}<small>MIN</small></b>`},1000)}
